- name: Update launchd service for Lima socket_vmnet
  hosts: macmini-01
  become: yes
  tasks:
    - name: Unload existing launchd service if it exists
      command: launchctl unload /Library/LaunchDaemons/com.homelab.lima.socket_vmnet.bridge0.plist
      changed_when: false
      failed_when: false # Don't fail if the service wasn't loaded

    - name: Copy updated launchd plist file
      copy:
        src: ../updated.com.homelab.lima.socket_vmnet.bridge0.plist
        dest: /Library/LaunchDaemons/com.homelab.lima.socket_vmnet.bridge0.plist
        owner: root
        group: wheel
        mode: '0644'

    - name: Load launchd service
      command: launchctl load -w /Library/LaunchDaemons/com.homelab.lima.socket_vmnet.bridge0.plist
      changed_when: true
